repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        entry: bash -c 'black . && djlint . --reformat --format-css || true'
        language: system
        stages: [commit]
        pass_filenames: false
    -   id: mypy
        name: mypy
        entry: bash -c 'cd app/capstone && mypy .'
        language: system
        stages: [commit]
        pass_filenames: false
    -   id: test
        name: test
        entry: bash -c 'cd app/capstone && python manage.py test'
        language: system
        stages: [commit]
        pass_filenames: false
    -   id: update
        name: update
        entry: bash -c 'cd app && pip freeze > requirements.txt'
        language: system
        stages: [commit]
        pass_filenames: false
