# Generated by Django 4.2.5 on 2023-10-12 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0002_uploadedfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.RemoveField(
            model_name="file",
            name="path",
        ),
        migrations.AddField(
            model_name="file",
            name="file",
            field=models.FileField(
                default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
