# Generated by Django 4.2.5 on 2023-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0007_alter_conversion_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_output",
            field=models.BooleanField(default=False),
        ),
    ]
