# Generated by Django 4.2.5 on 2023-10-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0008_file_is_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
