# Generated by Django 4.2.5 on 2023-10-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0009_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(max_length=500, upload_to=""),
        ),
    ]
