# Generated by Django 4.2.5 on 2023-11-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0010_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('get_display_number', models.IntegerField()),
                ('get_display_price', models.FloatField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('phrase', models.TextField()),
            ],
        ),
    ]
