# Generated by Django 4.2.5 on 2023-11-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0011_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='title',
        ),
    ]
