# Generated by Django 4.2.5 on 2023-11-30 19:21

from django.db import migrations

def import_products(app, schema_editor):
    Products = app.get_model("transformer", "Products")
    daily = Products.objects.create(name='Daily Subscription', get_display_number=1000, get_display_price=4.99, description='Get access to Platonix for 1 day', phrase='Most Flexible!')
    monthly = Products.objects.create(name='Monthly Subscription', get_display_number=30000, get_display_price=14.99, description='Get access to Platonix for 1 month', phrase='Most Popular!')
    yearly = Products.objects.create(name='Yearly Subscription', get_display_number=100000, get_display_price=114.99, description='Get access to Platonix for 1 year', phrase='Best Value!')

class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0012_remove_products_title'),
    ]

    operations = [
        migrations.RunPython(import_products),
    ]
