# Generated by Django 4.2.5 on 2024-01-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0013_auto_20231130_1121"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_input",
            field=models.BooleanField(default=False),
        ),
    ]
