# Generated by Django 4.2.5 on 2024-01-14 05:55

from django.db import migrations

def import_products(app, schema_editor):
    Product = app.get_model("transformer", "Product")
    daily = Product.objects.create(
        name="Daily Subscription",
        get_display_number=1000,
        get_display_price_cents=499,
        get_display_price=4.99,
        description="Get access to Platonix for 1 day",
        phrase="Most Flexible!",
    )
    monthly = Product.objects.create(
        name="Monthly Subscription",
        get_display_number=30000,
        get_display_price_cents=1499,
        get_display_price=14.99,
        description="Get access to Platonix for 1 month",
        phrase="Most Popular!",
    )
    yearly = Product.objects.create(
        name="Yearly Subscription",
        get_display_number=100000,
        get_display_price_cents=11499,
        get_display_price=114.99,
        description="Get access to Platonix for 1 year",
        phrase="Best Value!",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0015_product_get_display_price_cents_and_more'),
    ]

    operations = [
        migrations.RunPython(import_products),
    ]
