# Generated by Django 4.2.5 on 2024-02-06 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0014_profile"),
        ("transformer", "0015_alter_conversion_date_alter_file_date_and_more"),
    ]

    operations = []
