# Generated by Django 4.2.5 on 2024-02-02 21:51

from django.db import migrations

def update_products(app, schema_editor):
    Product = app.get_model("transformer", "Product")
    Product.objects.all().delete()
    daily = Product.objects.create(
        name="Daily Subscription",
        get_display_price_cents=99,
        get_display_price=0.99,
        description="Get access to Platonix for 1 day",
        phrase="Most Flexible!",
        length_days=1
    )
    monthly = Product.objects.create(
        name="Monthly Subscription",
        get_display_price_cents=499,
        get_display_price=4.99,
        description="Get access to Platonix for 1 month",
        phrase="Most Popular!",
        length_days=30
    )


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0018_remove_product_get_display_number_and_more'),
    ]

    operations = [
         migrations.RunPython(update_products),
    ]
