# Generated by Django 4.2.5 on 2024-02-08 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0015_alter_conversion_date_alter_file_date_and_more"),
        ("transformer", "0019_auto_20240202_1351"),
    ]

    operations = []
