# Generated by Django 4.2.5 on 2024-02-13 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0016_merge_20240206_2309"),
        ("transformer", "0020_merge_20240208_1240"),
    ]

    operations = []
