# Generated by Django 4.2.5 on 2024-02-25 20:33

from django.db import migrations

def update_products(app, schema_editor):
    Product = app.get_model("transformer", "Product")
    premium = Product.objects.create(
        name="Premium Subscription",
        get_display_price_cents=999,
        get_display_price=9.99,
        description="Get access to Platonix for 1 month",
        phrase="Unlock the power of GPT-4!",
        length_days=1,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0021_merge_20240213_0555'),
    ]

    operations = [
        migrations.RunPython(update_products),
    ]
