# Generated by Django 4.2.5 on 2024-02-26 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0016_alter_file_conversion"),
        ("transformer", "0021_merge_20240213_0555"),
    ]

    operations = []
