# Generated by Django 4.2.5 on 2024-03-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0022_merge_20240226_1454"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversion",
            name="user_parameters",
        ),
        migrations.AddField(
            model_name="conversion",
            name="complexity",
            field=models.IntegerField(
                choices=[
                    (0, "Very Basic"),
                    (1, "Basic"),
                    (2, "Moderate"),
                    (3, "Default"),
                    (4, "Highly Advanced"),
                    (5, "Very Detailed"),
                    (6, "Extremely Detailed"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="image_frequency",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "A Few"),
                    (2, "Some"),
                    (3, "Default"),
                    (4, "Many"),
                    (5, "Numerous"),
                    (6, "Lots"),
                ],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="language",
            field=models.CharField(
                choices=[
                    ("Auto", "Auto"),
                    ("English", "English"),
                    ("French", "French"),
                    ("Spanish", "Spanish"),
                ],
                default="Auto",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="model",
            field=models.CharField(
                choices=[
                    ("gpt-3.5-turbo-0125", "GPT-3.5"),
                    ("gpt-4-0125-preview", "GPT-4"),
                ],
                default="gpt-3.5-turbo-0125",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="num_slides",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="conversion",
            name="prompt",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="conversion",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_conversions",
                to="transformer.file",
            ),
        ),
        migrations.AddField(
            model_name="conversion",
            name="tone",
            field=models.CharField(
                choices=[
                    ("Auto", "Auto"),
                    ("Fun", "Fun"),
                    ("Creative", "Creative"),
                    ("Casual", "Casual"),
                    ("Professional", "Professional"),
                    ("Formal", "Formal"),
                ],
                default="Auto",
                max_length=50,
            ),
        ),
    ]
