# Generated by Django 4.2.5 on 2024-03-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0023_remove_conversion_user_parameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="slides_contents",
            field=models.JSONField(default=dict),
        ),
    ]
