# Generated by Django 5.0.3 on 2024-04-04 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0023_remove_conversion_user_parameters_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("prompt", models.TextField(default="")),
                ("num_questions", models.IntegerField(default=3)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-3.5-turbo-0125", "GPT-3.5"),
                            ("gpt-4-0125-preview", "GPT-4"),
                        ],
                        default="gpt-3.5-turbo-0125",
                        max_length=50,
                    ),
                ),
                (
                    "complexity",
                    models.IntegerField(
                        choices=[
                            (0, "Very Basic"),
                            (1, "Basic"),
                            (2, "Moderate"),
                            (3, "Default"),
                            (4, "Highly Advanced"),
                            (5, "Very Detailed"),
                            (6, "Extremely Detailed"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Auto", "Auto"),
                            ("English", "English"),
                            ("French", "French"),
                            ("Spanish", "Spanish"),
                        ],
                        default="Auto",
                        max_length=50,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_exercise",
                        to="transformer.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
