# Generated by Django 5.0.3 on 2024-04-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0025_exercisefile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise",
            old_name="num_questions",
            new_name="num_multiple_choice",
        ),
        migrations.AddField(
            model_name="exercise",
            name="num_short_ans",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="exercise",
            name="num_true_false",
            field=models.IntegerField(default=3),
        ),
    ]
