# Generated by Django 4.2.5 on 2024-04-06 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0024_conversion_slides_contents"),
        (
            "transformer",
            "0026_rename_num_questions_exercise_num_multiple_choice_and_more",
        ),
    ]

    operations = []
