# Generated by Django 4.2.5 on 2024-04-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transformer", "0027_merge_20240406_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="slides_contents",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="file",
            name="exercise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="transformer.exercise",
            ),
        ),
        migrations.DeleteModel(
            name="ExerciseFile",
        ),
    ]
