name: Auto Code Formatting

on:
  push:
    branches:
      - '*'
      
permissions:
  contents: write

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
     
      - name: Format code with Black
        run: black .

      - name: Format HTML with djlint
        run: djlint . --reformat --format-css || true

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add .

          # Check if there are changes to commit
          if git diff-index --quiet HEAD; then
            echo "No code changes to commit."
          else
            git commit -m "Auto-format code"
            git push
          fi
