name: Auto Code Formatting

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Format code with Black
        run: black .

      - name: Format HTML with djlint
        run: djlint . --reformat --format-css --format-js

      - name: Check for changes
        run: git diff --exit-code

      - name: Commit and push changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your.email@example.com'
          git add .
          git commit -m "Apply code formatting"
          git push
        env:
          DATABASE_URL: "postgres://postgres:password@localhost:5432/dev"
