name: Auto Code Formatting

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-formatting:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: dev
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Format code with Black
      run: black .

    - name: Format HTML with djhtml
      run: djhtml .

    - name: Check for changes
      run: git diff --exit-code

    - name: Commit and push changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
        git add .
        git commit -m "Apply code formatting"
        git push

      env:
        DATABASE_URL: "postgres://postgres:password@localhost:5432/dev"
